# Generated by Django 6.0.2 on 2026-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="tech_courses/")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("physical", "Physical"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.CharField(help_text="e.g. 6 Weeks", max_length=100),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("availability", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-featured", "-created_at"],
            },
        ),
    ]
